server:
  port: 8081
  servlet:
    context-path: /rentacar/api
spring:
  application:
    name: RentACar
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar
    username: postgres
    password: postdba
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: false
springdoc:
  api-docs:
    path: /docs
    pathsToMatch: /api/**
  swagger-ui:
    use-root-path: true
    path: /swagger
